### ISSUE TITLE
[ENTRY REQUEST]

### ISSUE THREAD

**Issue by tmyuu** [glifio/infinity-pool-gov#2]
#### Testnet Agent Address / ID
*(0x128F443d949396BD05eC1Cb422433737FF7ce16E / 9)*

#### Mainnet Agent Address / ID
*(0x202ECe27F97eCDaDB5EC221e8C917e0Ae2C51693 / 4)*

#### Desired borrow amount
*(100FIL at the present stage / 540 days )*

#### Sealing rate
*(1TiB per a day)*

#### Prerequisites
- [x] I understand the rules of the GLIF Pools Protocol and the Infinity Pool
- [x] I understand that I must pay the fees I owe to the pool at least once a week
- [x] I understand that if I owe more than 3 weeks worth of fees to the pool, my miner(s) and agent are at risk of liquidation
- [x] I understand that if I have 3 or more days of consecutive faulty sectors, my miner(s) and agent are at risk of liquidation
- [x] I have gone through the necessary prerequisite actions on the testnet

#### Contact info
*(info@livspect.com)*<br />
*(@Yushi - Livspect)*<br />
*(@livspect)*<br />
*(Slack or Twitter)*<br />

**Comment by Schwartz10** [comment]
Thank you @tmyuu ! Your level has been set to 1, and you are approved to enter the pool when you're ready
