### ISSUE TITLE
[ENTRY REQUEST]

### ISSUE THREAD

**Issue by chijr** [glifio/infinity-pool-gov#26]
#### Testnet Agent Address / ID
*(Please provide the Testnet Agent Address / ID)*

#### Mainnet Agent Address / ID
*(Please provide the Mainnet Agent Address / ID)*
f4 address:   f410fjsnknyja3cwvnnrfbv5fgh3bxwovmyidpuiopma
Agent GLIF ID:    97

#### Desired borrow amount
*(Please tell us how much you intend to borrow, and over what time period)*
Total FIL is 89211, and more nodes will be added later. We want to borrow 70% of the total, with a duration of 1 year.

#### Sealing rate
*(What is your miners sealing speed?)*
72.27 TiB/D

#### Prerequisites
- [ Y] I understand the rules of the GLIF Pools Protocol and the Infinity Pool
- [ Y] I understand that I must pay the fees I owe to the pool at least once a week
- [ Y] I understand that if I do not pay the fees I owe to the pool once a week, my rate will increase (and I will pay more in fees as a result)
- [ Y] I understand that if I owe more than 3 weeks worth of fees to the pool, my miner(s) and agent are at risk of liquidation
- [ Y] I understand that if I have 3 or more days of consecutive faulty sectors, my miner(s) and agent are at risk of liquidation
- [ Y] I have pledged a miner that has reached the minimum power threshold to my Agent on mainnet

#### Contact info
*(Email address)*   chijingruo@gmail.com<br />
*(Discord ID + tag)* <br />
*(Twitter)*  <br />
*(Preferred communication channel)* <br />

**Comment by Schwartz10** [comment]
@chijr this request has been approved. The quota will be bumped within the next couple hours

**Comment by chijr** [comment]
Debt-to-liquidation-value (LTV)       53.769% (must stay below 80%)   
Debt-to-equity (DTE)                  92.177% (must stay below 200%)  
Debt-to-income (DTI)                  26.097% (must stay below 25%)

Debt-to-income is above  25%，  My Status   is healthy?

**Comment by Schwartz10** [comment]
Hey @chijr - we should probably improve the CLI to give a warning that you're over the DTI ratio. However, we only consider you "unhealthy" if you're losing significant power and/or getting close to 100% LTV - we'll reach out to you if your agent is in a dangerous state

As for the DTI - until this gets back under 25%, you wont be able to borrow, withdraw, or remove miners from your Agent. Best thing to do is either:
1. Add more miners that have power and are earning block rewards
2. Pay back some borrowed FIL to lower your principal 

Feel free to keep commenting in this issue if you have any more questions. You can also reach out to me on telegram @jpschwartz or over email jonathan@glif.io too! Thanks for checking in
