### ISSUE TITLE
[Borrow FIL Request]

### ISSUE THREAD

**Issue by icecreamweb3** [glifio/infinity-pool-gov#29]
#### Testnet Agent Address / ID
*(Please provide the Testnet Agent Address / ID)*

#### Mainnet Agent Address / ID
f03069372

#### Desired borrow amount
40,000FIL 12 Months

#### Sealing rate
500TB / Day

#### Prerequisites
- [*] I understand the rules of the GLIF Pools Protocol and the Infinity Pool
- [*] I understand that I must pay the fees I owe to the pool at least once a week
- [*] I understand that if I do not pay the fees I owe to the pool once a week, my rate will increase (and I will pay more in fees as a result)
- [*] I understand that if I owe more than 3 weeks worth of fees to the pool, my miner(s) and agent are at risk of liquidation
- [*] I understand that if I have 3 or more days of consecutive faulty sectors, my miner(s) and agent are at risk of liquidation
- [*] I have pledged a miner that has reached the minimum power threshold to my Agent on mainnet

#### Contact info
kreamliao@gmail.com<br />
None<br />
None<br />
email<br />

**Comment by twosson** [comment]
@Schwartz10 Please help approve as soon as possible. 🙏
