### ISSUE TITLE
thank you, I need use it.

### ISSUE THREAD

**Issue by tianzyt** [glifio/infinity-pool-gov#33]
## Infinity Pool Entry Request
﻿
#### Testnet Agent Address / ID
*(Please provide the Testnet Agent Address / ID)*
161﻿

#### Mainnet Agent Address / ID
*(Please provide the Mainnet Agent Address / ID)*
f01930832
#### Desired borrow amount
*(Please tell us how much you intend to borrow, and over what time period)*
6000-12000
#### Sealing rate
*(What is your miners sealing speed?)*
5T/day
#### Prerequisites
- [x] I understand the rules of the GLIF Pools Protocol and the Infinity Pool
- [x] I understand that I must pay the fees I owe to the pool at least once a week
- [x] I understand that if I do not pay the fees I owe to the pool once a week, my rate will increase (and I will pay more in fees as a result)
- [x] I understand that if I owe more than 3 weeks worth of fees to the pool, my miner(s) and agent are at risk of liquidation
- [x] I understand that if I have 3 or more days of consecutive faulty sectors, my miner(s) and agent are at risk of liquidation
- [x] I have pledged a miner that has reached the minimum power threshold to my Agent on mainnet
﻿
#### Contact info
*(Email address):276351890@qq/com
﻿
﻿

**Comment by tianzyt** [comment]
When can I borrow coins? There is only 100 quota now.

**Comment by Schwartz10** [comment]
@tianzyt all set now!
