### ISSUE TITLE
[ENTRY REQUEST] 

### ISSUE THREAD

**Issue by KimDaeikk** [glifio/infinity-pool-gov#35]
#### Testnet Agent Address / ID
*(Please provide the Testnet Agent Address / ID)*

#### Mainnet Agent Address / ID
*(Please provide the Mainnet Agent Address / ID)*
165, 170

#### Desired borrow amount
*(Please tell us how much you intend to borrow, and over what time period)*
250000 FIL (expect to onboarding 40PB)

#### Sealing rate
*(What is your miners sealing speed?)*
165 agent : 6 ~ 7 TB
170 agent : 4 ~ 5 TB

#### Prerequisites
- [v] I understand the rules of the GLIF Pools Protocol and the Infinity Pool
- [v] I understand that I must pay the fees I owe to the pool at least once a week
- [v] I understand that if I do not pay the fees I owe to the pool once a week, my rate will increase (and I will pay more in fees as a result)
- [v] I understand that if I owe more than 3 weeks worth of fees to the pool, my miner(s) and agent are at risk of liquidation
- [v] I understand that if I have 3 or more days of consecutive faulty sectors, my miner(s) and agent are at risk of liquidation
- [v] I have pledged a miner that has reached the minimum power threshold to my Agent on mainnet

#### Contact info
*(Email address)*<br /> dylan@zetacube.net
*(Discord ID + tag)*<br /> zecu_97366
*(Twitter)*<br />
*(Preferred communication channel)*<br /> https://www.zetacube.net/

**Comment by KimDaeikk** [comment]
It's an additional question
To reach 100FIL, the minimum borrow now max value.
How many pledge do I need at least ?
(I just want to ask my SPs for the minimum amount of collateral they need)
(start sealing with SPs own FIL -> borrow now reach +100 -> sealing with borrowed 100 FIL -> borrow now reach +100... repeatly)

**Comment by Schwartz10** [comment]
Hey @KimDaeikk great question! 

There is a V2 system upgrade coming out at the end of august, where the maximum leverage will be 3x, so to borrow 100 FIL, you would need 34 FIL in collateral

The V1 system now is 2x maximum leverage, so to borrow 100 FIL you would need 50 FIL in collateral

Your Agents quotas will be updated in the next 6 hours

**Comment by Schwartz10** [comment]
@KimDaeikk all set - i'll leave this ticket open in case you have other questions

**Comment by KimDaeikk** [comment]
Hello! We are ZetaCube, a supplier of SP hardware. We are planning a service that provides continuous profits by onboarding customers who provide high-spec hardware and minimal collateral. To achieve this, we intend to use collateral from the Glif team. We have some questions:

"The V1 system now has a maximum leverage of 2x, so to borrow 100 FIL, you would need 50 FIL in collateral." Is it correct that the maximum leverage means the maximum borrow amount? And how can we borrow the maximum amount?

If I borrow the maximum amount, I think the LTV (Loan-to-Value), DTE (Debt-to-Equity), and DTI (Debt-to-Income) ratios would be very high. How can we control these ratios?

Before borrowing reaches 100 FIL, an amount equivalent to the equity can be borrowed. After borrowing exceeds 100 FIL, only half of the equity can be borrowed. We want to continue sealing without requiring our customers to provide additional FIL. However, based on this system, we can't maintain sealing (e.g., borrowing 100 -> 50 -> 25 -> 12.5 -> ...). It seems impossible to reach 250,000 FIL without additional FIL input. Do you have any solutions for this problem?

Regarding the first question, you mentioned I need 50 FIL to borrow 100 FIL. However, the "glif agent info" returns a lower borrow amount than 100 FIL. I can't infer the logic behind this. Could you clarify?

![image](https://github.com/glifio/infinity-pool-gov/assets/166095932/e3391239-d24a-4197-8476-b35b27442794)
![image](https://github.com/glifio/infinity-pool-gov/assets/166095932/1ae231d1-0f53-4f02-b92f-dab0f9b6e6c4)


We need to know about borrowing large amounts before Thursday due to the notary’s expiration.

**Comment by Schwartz10** [comment]
Hey! Great questions, so a few things to mention:

1. After you borrow FIL, you have two options - use the FIL for sealing, or withdraw the FIL from your Agent outside of the system

When you use FIL for sealing, you can use the `glif agent miners push-funds` command to move FIL from your Agent into one of your miners to use for sealing. When you keep the FIL within your Agent, you are not removing equity from your agent, and the newly borrowed FIL gets added to your agent's liquidation value. This will allow you to borrow a lot more FIL than withdrawing.

When you withdraw FIL from your Agent, you're _removing_ equity from your Agent, which means you won't be able to get 2x leverage. 

2. DTI

We understand DTI has been capping some SPs from borrowing up to 2x leverage. We're working on immediate solutions (and I will get back to you this week on potential immediate solutions), but DTI is generally being phased out in our V2 system, which will go live at the end of august. 

In V2:
- No more weekly payments required
- DTI will not cap you from reaching your maximum leverage
- 3x leverage 

Let me know if you have other questions! You can also message me directly on telegram (@jpschwartz) or discord

**Comment by dik654** [comment]
Infinity Pool Entry Request
Testnet Agent Address / ID
(Please provide the Testnet Agent Address / ID)

Mainnet Agent Address / ID
(Please provide the Mainnet Agent Address / ID)
216

Desired borrow amount
(Please tell us how much you intend to borrow, and over what time period)
250000 FIL (expect to onboarding 40PiB)

Sealing rate
(What is your miners sealing speed?)
216 agent : 6 ~ 7 TB

Prerequisites
[v] I understand the rules of the GLIF Pools Protocol and the Infinity Pool
[v] I understand that I must pay the fees I owe to the pool at least once a week
[v] I understand that if I do not pay the fees I owe to the pool once a week, my rate will increase (and I will pay more in fees as a result)
[v] I understand that if I owe more than 3 weeks worth of fees to the pool, my miner(s) and agent are at risk of liquidation
[v] I understand that if I have 3 or more days of consecutive faulty sectors, my miner(s) and agent are at risk of liquidation
[v] I have pledged a miner that has reached the minimum power threshold to my Agent on mainnet
Contact info
(Email address)
[dylan@zetacube.net](mailto:dylan@zetacube.net)
(Discord ID + tag)
zecu_97366
(Twitter)

(Preferred communication channel)
https://www.zetacube.net/
