### ISSUE TITLE
[ENTRY REQUEST]

### ISSUE THREAD

**Issue by Brian44913** [glifio/infinity-pool-gov#4]
#### Testnet Agent Address / ID
*(Please provide the Testnet Agent Address / ID)*

#### Mainnet Agent Address / ID
0x497E6FBD6E310412FBc5030e359C8a736409A9fa / 10

#### Desired borrow amount
72,000 FIL for now / 540 days

#### Sealing rate
200T / day now, 500 T / day max

#### Prerequisites
- [x] I understand the rules of the GLIF Pools Protocol and the Infinity Pool
- [x] I understand that I must pay the fees I owe to the pool at least once a week
- [x] I understand that if I do not pay the fees I owe to the pool once a week, my rate will increase (and I will pay more in fees as a result)
- [x] I understand that if I owe more than 3 weeks worth of fees to the pool, my miner(s) and agent are at risk of liquidation
- [x] I understand that if I have 3 or more days of consecutive faulty sectors, my miner(s) and agent are at risk of liquidation
- [x] I have pledged a miner that has reached the minimum power threshold to my Agent on mainnet

**Comment by Schwartz10** [comment]
Hey @Brian44913 ! This request looks good - just sent you an email // discord friend request to discuss a couple details
