### ISSUE TITLE
[ENTRY REQUEST]

### ISSUE THREAD

**Issue by ratohe** [glifio/infinity-pool-gov#5]
Infinity Pool Entry Request

Mainnet Agent Address / ID
*0x491Bfe0C44Ffe6765013E98e2D64289d0A36De30/f02341447*

Desired borrow amount
*650fil for one year)*

Sealing rate
*768 Gib/day*
Prerequisites
- [x ] I understand the rules of the GLIF Pools Protocol and the Infinity Pool
- [x ] I understand that I must pay the fees I owe to the pool at least once a week
- [x ] I understand that if I do not pay the fees I owe to the pool once a week, my rate will increase (and I will pay more in fees as a result)
- [ x] I understand that if I owe more than 3 weeks worth of fees to the pool, my miner(s) and agent are at risk of liquidation
- [x ] I understand that if I have 3 or more days of consecutive faulty sectors, my miner(s) and agent are at risk of liquidation
- [x ] I have pledged a miner that has reached the minimum power threshold to my Agent on mainnet
Contact info
*ratohe@web.de*<br />
*854292932157112320+ ratohe*<br />
*(Twitter)*<br />
*ratohe@web.de*<br />

**Comment by Schwartz10** [comment]
Approved
